import type { Metadata } from "next";
import { ListChecks } from "lucide-react";
import { Card } from "@/components/ui/card";
import { PageHeading } from "@/components/page-heading";
import { StageNavigation } from "@/components/stage-navigation";

export const metadata: Metadata = { title: "Process & Validate" };

export default function ProcessPage() {
  return (
    <>
      <PageHeading step="02 / Process & Validate" title="Less cleanup. More consistency."
        description="This stage will turn the source exports into reporting-ready data using defined rules, while keeping unresolved exceptions visible for review." />
      <Card className="stage-placeholder">
        <span className="icon-tile mb-5"><ListChecks size={25} aria-hidden="true" /></span>
        <p className="status-label">Planned workflow</p>
        <h2 className="mt-3 text-2xl font-semibold tracking-tight">Processing is coming next.</h2>
        <p className="mt-3 max-w-xl text-sm leading-7 text-muted-foreground">The application shell is ready to explore. No transformations or validation have run, and no reporting data has been generated by this application.</p>
        <ul className="mt-7 grid gap-3 text-sm sm:grid-cols-2">
          <li className="planned-item">Normalize obvious SKU formatting</li>
          <li className="planned-item">Apply refund and cancellation rules</li>
          <li className="planned-item">Standardize expense aliases</li>
          <li className="planned-item">Retain missing-SKU exceptions for review</li>
        </ul>
      </Card>
      <p className="mt-5 text-sm leading-6 text-muted-foreground">Guest orders will be retained. Customer matching will use stable customer IDs, without guessing identities.</p>
      <StageNavigation index={1} />
    </>
  );
}
